In [2]:
import numpy as np
import pickle
import matplotlib.pyplot as plt

from sklearn import preprocessing
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from keras.callbacks import ModelCheckpoint
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten

In [9]:
"""
Open the training data.
"""
training_data_filepath = 'F:/ZaknafeinII_Backup_02-02-22/daea/training_data_generation/id16/output/flat_mfcc_training_data_dict.pickle'

with open(training_data_filepath, 'rb') as f:
    data_dict = pickle.load(f)
    
for key in data_dict:
    print(key, 'is of shape', data_dict.get(key).shape)

train_input is of shape (64, 180518)
val_input is of shape (64, 38683)
test_input is of shape (64, 38683)
train_targets is of shape (64, 180518)
val_targets is of shape (64, 38683)
test_targets is of shape (64, 38683)


In [37]:
# Program to show working of solve()
import numpy as np

# creating the array "a"
A = np.array([[3, 4, 5], [1, 2, 3], [2, 4, 5]])
B = np.array([[9, 8, 7], [9, 8, 7]])
print("Array A is: \n", A)
print(A.shape)
print("Array B is : \n", B)
print(B.shape)

# Calculating the equation
ans = np.linalg.tensorsolve(A, B)

# Printing the answer
print("Answer of the equation is  :\n", ans)

# Checking if the answer if correct
print(np.allclose(np.dot(A, ans), B))

Array A is: 
 [[3 4 5]
 [1 2 3]
 [2 4 5]]
(3, 3)
Array B is : 
 [[9 8 7]
 [9 8 7]]
(2, 3)


LinAlgError: Last 2 dimensions of the array must be square

In [35]:
"""
Calculate the ideal masks such that (input vals)*(mask coefficients)=(label vals)
So --> (mask coefficients)=(label vals)/(input vals)
"""
A = data_dict.get('train_targets')[0:64,0:64]
print('A shape:', A.shape)
m, n = A.shape[-2:]
print(A)
print('m=%i, n=%i' % (m, n))
B = data_dict.get('train_input')[0:64,0:2]
print('B shape:', B.shape)
# m, n = B.shape[-2:]
print(B)
# print('m=%i, n=%i' % (m, n))

X = np.linalg.tensorsolve(A, B)
print('X shape:', X.shape)
print(X)

A shape: (64, 64)
[[-2.9894034e+02 -3.0185275e+02 -2.6171429e+02 ... -2.2283923e+02
  -2.2049660e+02 -2.2354535e+02]
 [ 4.9950134e+01  5.6952148e+01  6.8272598e+01 ...  1.6560295e+02
   1.5805267e+02  1.5277945e+02]
 [ 1.5940108e+01  9.8693981e+00 -5.0024490e+01 ... -3.2679035e+01
  -2.9702023e+01 -2.0342117e+01]
 ...
 [ 1.5344205e+00  1.9326158e+00 -2.0040065e-02 ...  2.4316421e+00
   5.4558592e+00  4.2094002e+00]
 [-5.5452642e+00 -4.0141487e+00 -6.6619766e-01 ... -1.9025437e+00
   4.4040799e-01  1.4309230e+00]
 [ 6.0375633e+00  5.6048183e+00  3.2592940e+00 ... -2.7059088e+00
  -4.7231016e+00  5.6993842e-01]]
m=64, n=64
B shape: (64, 2)
[[-2.9912003e+02 -3.0206839e+02]
 [ 5.0201698e+01  5.7252682e+01]
 [ 1.5696068e+01  9.5817833e+00]
 [ 7.9924065e+01  7.3699150e+01]
 [-2.8930542e+01 -2.7994225e+01]
 [ 4.2266335e+01  3.8264481e+01]
 [ 5.9936352e+00  2.1191211e+00]
 [ 2.5325522e-01 -1.9750403e+00]
 [-1.2531159e+01 -9.2354507e+00]
 [ 2.6886223e+01  1.6751850e+01]
 [-9.5093918e+00 -1.3711

LinAlgError: Last 2 dimensions of the array must be square