In [18]:
""" import necessary libraries """

import os
import soundfile as sf
import librosa
from pydub import AudioSegment
import numpy as np


In [26]:
""" iterate over voxceleb2 directory """

# user-specific variables
pc_specific_path = 'C:/Users/eholy/Desktop/SD/vox2/vox2_dev_aac_partaa~/dev/aac'
output_path = 'C:/Users/eholy/Desktop/SD/voxshattered/'
frame_rate = 22050
num_frames = 5292000

# iterable object creation to iterate over each person's folder in the the dataset
character_ids = os.listdir(pc_specific_path)

for character_id in character_ids:
    
    summed_duration = 0
    merged_wav = np.array([]) # used to hold all of the wav files that have been iterated over
    
    curr_char_dir = pc_specific_path + '/' + character_id
    length_flag = False
    # iterate over each audio directory belonging to that character (different interviews, etc)
    char_specific_clips = os.listdir(curr_char_dir)
    
    for clip_folder in char_specific_clips:
        # iterative over the wav files in each clip folder
        clips = os.listdir(curr_char_dir + '/' + clip_folder)
        for clip in clips:
            clip_filepath = curr_char_dir + '/' + clip_folder + '/' + clip

            # load audio file and standardize the frame rate
            audio = AudioSegment.from_file(clip_filepath).set_frame_rate(frame_rate)
            audio_array = np.array(audio.get_array_of_samples())
            sf.write(output_path + str(character_id) + '/' + str(character_id) + '_' + 'rewrite' + '.wav', audio_array, frame_rate)
            
            if not merged_wav.any():
                merged_wav = audio_array
            else:
                merged_wav = np.append(merged_wav, audio_array)
            print('audio_array - first index: ' + str(audio_array[0]) + ' shape: ', audio_array.shape)


            summed_duration += len(audio_array)

            #merged_wav = np.concatenate((merged_wav, audio_array), axis=None)
            
            print(merged_wav)
            print('actual merge- first index: ' + str(merged_wav[0]) + ' shape: ', merged_wav.shape)
            sf.write(output_path + str(character_id) + '/' + str(character_id) + '_' + 'test' + '.wav', merged_wav, frame_rate)

            if summed_duration > 1000000:

                length_flag = True
                break
            
                
        break
        
        if length_flag:
                break
    
    break

audio_array - first index: -1413 shape:  (122774,)
[-1413 -1620 -1623 ...   -17   -16   -12]
actual merge- first index: -1413 shape:  (122774,)
audio_array - first index: 1362 shape:  (170754,)
[-1413 -1620 -1623 ...    -2    -3    -4]
actual merge- first index: -1413 shape:  (293528,)
audio_array - first index: -66 shape:  (338687,)
[-1413 -1620 -1623 ...     0     0     0]
actual merge- first index: -1413 shape:  (632215,)
audio_array - first index: 958 shape:  (191922,)
[-1413 -1620 -1623 ...   -11    -7    -3]
actual merge- first index: -1413 shape:  (824137,)
audio_array - first index: 735 shape:  (230025,)
[-1413 -1620 -1623 ...     0     0     0]
actual merge- first index: -1413 shape:  (1054162,)
